service: lambda-service
package:
  exclude:
    - node_modules/**
provider:
  name: aws
  apiGateway:
    shouldStartNameWithService: true
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: default

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:us-east-1:xxxxxxxxxx:layer:MomentLayer:1